apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lyrics-bio
resources:
  - lyrics-bio.yaml"
  - secret.yaml"
  - mariadb-secret.yaml"
helmCharts:
  - name: mariadb
    releaseName: mariadb
    version: 11.4.2
    repo: https://charts.bitnami.com/bitnami
    namespace: lyrics-bio
    valuesFile: values.yaml
