apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: imagepullsecret-patcher
spec:
  encryptedData:
    .dockerconfigjson: AgBpt866VLJWnmXSnOhDOefWKZoE02PZckrcAg6ZZLzHO83mpsKzec6zgSmsxbFPqLawtBHYq+iO0J9JqmJiI/HFaugdgi8YqNMTwwDj8O9KNJUpk46n16mJWj+pR5CFvKMYt3VQLbiWAJzfa6gQtLg9PPafP0U3/ZsnDtdPCR0zKzsseE3AFyXKypV3j5bBB5oqNk3MYQWr4Tq8mKShsIQlIZtMm93Q93VaOV6Us2d7Ah6n48AoHbMtZZf0qjWj6q+aeF+YiVBBW2sgDbMxI6x5J3YL429TZpj3kW+tnSWsmjCSgaCeC663i+I5D/QJJ7k9HXY6Yy/ecxqfXNAGVSS58XNsHXhZCnVWWqluWqOZuLPxLoo97mO//cyWg1R0F81I6f6Ud3w/bu4d/JA8723NFkUuNqbipS5TYDfzTj8wsDE5PBDkHx3hMJl7KciP0hDFs3zTUd1QDPkoRk6mns3v0AkaMLdDmMwPO8LsNzf44Py/iSTLAjTCU2x66kaXYo6mGbjZ8nL9d2uELbn+LImLVXLvjj4KBeWtyCx7OfjYLznO8E1AfiKj3FXzqV5g7E+Haabffk8mZW0116bW/fwR+LX8Yq0IVzVuVrQH3QSHK84gkvO/TAM869Uhve0yyAId7w7x/SNRCHGTngSiERcTgry9EdSIMF+aOgnCRw8lENx4SKqGsVU/6O1pX/gXvcvR/oZXKvSXkV4kYzpuoDZIpheRfHo3VUPZXkIGsZFCzd1q/08WWTUPXNfjDtWmaUuHfOK7WkGKNTMYbJMEi9GSfKYt01uAOWjz5GpAQ2lShOoF7r6XQa50xWYkcAYdraYlBvS//D+HdP9qBpcRY7g3FZLj8faM7EuEe5qnbWXKZjRue2gtbalfs98nAuYvOMsMdyz2cpNUnOO4WvM+IeIOkDK0q2VZuL9Ra47PhKEItP9AjjZXcmsebqsBczpvow==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: imagepullsecret-patcher
    type: kubernetes.io/dockerconfigjson

