apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: kube-system
spec:
  defaultCertificate:
    secretName: cert-key-nycode-dev
  certificates:
    - secretName: cert-key-marie-cologne
