apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - ns.yaml
  - authentik-secret.yaml
helmCharts:
  - name: authentik
    releaseName: authentik
    version: 2023.1.2
    repo: https://charts.goauthentik.io/
    namespace: authentik
    valuesFile: values.yaml
patchesStrategicMerge:
  - patches.yaml
