apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: miniflux
resources:
  - ns.yaml
  - admin.yaml
  - oauth2.yaml
helmCharts:
  - name: miniflux
    releaseName: miniflux
    version: 0.2.1
    repo: https://charts.nycode.dev/
    namespace: miniflux
    valuesFile: values.yaml
