apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/int128/argocd-commenter//config/default?ref=v1.9.0
  - argocd-commenter-secret.yaml
patchesStrategicMerge:
  - "argocd-commenter-image-fix.yaml"
namespace: argocd-commenter-system
