apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/int128/argocd-commenter/releases/download/v1.14.5/argocd-commenter.yaml
  - argocd-commenter-secret.yaml
namespace: argocd-commenter-system
