apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/int128/argocd-commenter/blob/v1.9.0/config/default/kustomization.yaml
  - argocd-commenter-secret.yaml
namespace: argocd-commenter-system
