apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/int128/argocd-commenter/config/default?ref=v1.9.0
  - argocd-commenter-secret.yaml
namespace: argocd-commenter-system
