apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
helmCharts:
  - name: prometheus-node-exporter
    releaseName: node-exporter
    version: 4.15.1
    repo: https://prometheus-community.github.io/helm-charts
    namespace: prometheus
    valuesInline:
      prometheus:
        monitor:
          enabled: true
