apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nycode-dev
  namespace: kube-system
spec:
  dnsNames:
    - nycode.dev
    - '*.nycode.dev'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: cert-key-nycode-dev
