apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - cloudflare-secret.yaml
  - cluster-issuer.yaml
helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    version: v1.10.2
    repo: https://charts.jetstack.io
    namespace: cert-manager
    valuesFile: values.yaml
    includeCRDs: true
