apiVersion: v1
kind: Namespace
metadata:
  name: traewelling-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traewelling-exporter
  namespace: traewelling-exporter
  labels:
    app.kubernetes.io/name: traewelling-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traewelling-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traewelling-exporter
    spec:
      containers:
        - name: traewelling-exporter
          image: ghcr.io/nycodeghg/traewelling-exporter/exporter:0.2.1
          ports:
            - containerPort: 3000
              name: metrics
              protocol: TCP
          envFrom:
            - secretRef:
                name: traewelling-exporter
          livenessProbe:
            httpGet:
              port: metrics
              scheme: HTTP
              path: /healthz
          readinessProbe:
            httpGet:
              port: metrics
              scheme: HTTP
              path: /healthz
---
apiVersion: v1
kind: Service
metadata:
  name: traewelling-exporter
  namespace: traewelling-exporter
  labels:
    app.kubernetes.io/name: traewelling-exporter
spec:
  selector:
    app.kubernetes.io/name: traewelling-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traewelling-exporter
  namespace: traewelling-exporter
  labels:
    app.kubernetes.io/name: traewelling-exporter
spec:
  endpoints:
    - honorLabels: true
      port: metrics
      path: /metrics
      scheme: http
      interval: 30s
  jobLabel: traewelling-exporter
  selector:
    matchLabels:
      app.kubernetes.io/name: traewelling-exporter
  namespaceSelector:
    matchNames:
      - traewelling-exporter
