apiVersion: v1
kind: Namespace
metadata:
  name: traewelling-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traewelling-exporter
  namespace: traewelling-exporter
  labels:
    app.kubernetes.io/name: traewelling-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traewelling-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traewelling-exporter
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      dnsPolicy: Default
      containers:
        - name: traewelling-exporter
          image: ghcr.io/nycodeghg/traewelling-exporter/exporter:0.4.0@sha256:e79be170b3224350ab2c076c72ce5c4a4d359c189eb7e1b3f3db27bde418fe12
          ports:
            - containerPort: 3000
              name: metrics
              protocol: TCP
          envFrom:
            - secretRef:
                name: traewelling-exporter
          livenessProbe:
            httpGet:
              port: metrics
              scheme: HTTP
              path: /healthz
          readinessProbe:
            httpGet:
              port: metrics
              scheme: HTTP
              path: /healthz
          resources:
            requests:
              cpu: "50m"
              memory: "10Mi"
            limits:
              cpu: "100m"
              memory: "20Mi"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: traewelling-exporter
  namespace: traewelling-exporter
  labels:
    app.kubernetes.io/name: traewelling-exporter
spec:
  selector:
    app.kubernetes.io/name: traewelling-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 3000
