apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgAt7bibRZ5zQSmInEWOpD1GSOkapVLERpgxAiXmpEzNOIBZWJeDUZcJlJQs7jvy4eQqsLUNfMGfkuY0pqGbSRe9WbSUiOGQwn3XNq6IptFkzMswt1UeEFyyD4FIr/vKgDzs/jRGe+vfOUDAXvsxfqAihdQ648HMBg54J7k8JwGPYN1OjlwpTc6fx2UJ10p4kTxIz/+Fy/3tjmghKPF+/V3pblWTNbKEKkL4C1iR9uXM5Vhi3U34UfbHlgMTVRlwMUO1odLEJ769bz5sfTZLGMuluRkq3J+eQ7+ckDQEMtXiQcke1QVZADQ0B7jaKE4bDp0XL2Y8yG209vpP+5IDwXY/LzEwown8y2d/1529t4Ux00PXM/KuFOwyh7EW7P29il5rl31ve43Y7rn4spfwHnimUvcpgTNcnrYncG7q43665ADKLKlPrV3cfR7q/6elMu9vtdnedmZQNeFaZz6Dl7/wnZA4sU97cFElOlwA4tx5wh+T2nFjbQwGExhKUmUDjQcUKeeJ9izMP+O35UkHg4NAKNGgj1PQ8gzCD0JzzsCtHgkmE/RGm4ehscchRd+wVcLc71TjZeVXS8/4Kva6NhhI5sMbnLIVygX1K4xooaeFjGeqhE7ha3SbtILUuQ9i/Xch3YI0ujEp9kORIn8HQJzr9b7m+FELgwiZia9e1Q4bGZLQ/koOx53WNbl57NYdWOToRc3GahWmCWew2TBbXgGzVGEGOr3/PUdRFpSkOpYR99OH7apmct+uQM3khMwk2eU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: argocd-webhook-secret
      namespace: argocd
    type: Opaque
