apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.4/manifests/install.yaml
  - argocd-route.yaml
  - argocd-extra-secret.yaml
  - argocd-repo.yaml
  - ns.yaml
  - apps/regenbogen-ice.yaml
  - apps/argocd.yaml
  - apps/argocd-commenter.yaml
patchesStrategicMerge:
  - argocd-cmd-params-cm-patch.yaml
  - argocd-config.yaml
namespace: argocd
