apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.4.6
  - argocd-route.yaml
  - argocd-extra-secret.yaml
  - argocd-repo.yaml
  - ns.yaml
  - apps
patchesStrategicMerge:
  - argocd-cmd-params-cm-patch.yaml
  - argocd-config.yaml
namespace: argocd
