apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: regenbogen-ice
  namespace: argocd
spec:
  destination:
    namespace: regenbogen-ice
    server: https://kubernetes.default.svc
  project: default
  source:
    path: regenbogen-ice
    repoURL: https://github.com/NyCodeGHG/server-deployments
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:  {}
