apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - ns.yaml
  - prom.yaml
  - alertmanager.yaml
  - alertmanager-discord-secret.yaml
  - ingresses.yaml
helmCharts:
  - name: alertmanager-discord
    releaseName: alertmanager-discord
    version: 1.3.2
    repo: https://k8s-at-home.com/charts/
    # language=yaml
    valuesInline:
      image:
        repository: ghcr.io/nycodeghg/alertmanager-discord
        tag: 1.0.2
      env:
        DISCORD_WEBHOOK:
          valueFrom:
            secretKeyRef:
              name: alertmanager-discord-secret
              key: DISCORD_WEBHOOK
        VERBOSE: "ON"
