apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: regenbogen-ice
resources:
  - ns.yaml
  - regenbogen-ice-secret-sealed.yaml
helmCharts:
  - name: regenbogen-ice
    releaseName: regenbogen-ice
    version: 1.10.0
    repo: https://mikbot.github.io/charts
    namespace: regenbogen-ice
    valuesFile: values.yaml
