apiVersion: apps/v1
kind: Deployment
metadata:
  name: regenbogen-ice
  namespace: regenbogen-ice
  labels:
    app.kubernetes.io/name: regenbogen-ice
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: regenbogen-ice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: regenbogen-ice
    spec:
      containers:
        - name: regenbogen-ice
          image: "ghcr.io/mikbot/regenbogen-ice:0.1.0"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: regenbogen-ice-secret
            - name: SENTRY_DSN
              value: ""
