apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
helmCharts:
  - name: kube-state-metrics
    releaseName: kube-state-metrics
    version: 4.26.0
    repo: https://prometheus-community.github.io/helm-charts
    namespace: prometheus
    valuesInline:
      prometheus:
        monitor:
          enabled: true
