apiVersion: apps/v1
kind: Deployment
metadata:
  name: hafas-graphql
  namespace: hafas-graphql
  labels:
    app: hafas-graphql
spec:
  replicas: 1
  template:
    metadata:
      name: hafas-graphql
      labels:
        app: hafas-graphql
    spec:
      containers:
        - name: hafas-graphql
          image: ghcr.io/nycodeghg/hafas-projects/hafas-graphql:0.1.0-nightly@sha256:8aaa5a1e49fa77e84549753fe7a391838379e560be549d8a8fee968d290c4a78
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: hafas-graphql
