apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-storage
allowVolumeExpansion: true
allowedTopologies: []
mountOptions: []
parameters:
  dataLocality: disabled
  fromBackup: ''
  fsType: ext4
  numberOfReplicas: '1'
  staleReplicaTimeout: '30'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
