apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBtruRHZV60MXTAnO4DlkMFak8v8p5L2i3sAkCzfXRZSnv0BmmSkAhC6878hQaK++g+KLia73iTsVBHjMqcPt60T3dpIT2nVNIxhJl1ZuCZRmXTHJEzSsME0CueHYObqoLGVLm2mY8W9DCD1fmDetZyGDENwuXGVP7Bjk/7dWH0PzUf62Z/f9rNXnyHvW8ntBeZIcGY4NFqN/Cbv/uEQ2ABdIRKFwrNpElS+YrX5QqtLySWiS2YeWudUwCPJMAvdSzn5GjTs57q/Z69roqB5yBbe+K9Hch1nK0Uglvl5g1KU4DAqwA7nY5jbAJVd2ILAr31AfkXkR3oesljq4PzM/zJzpj5m91hZtt/x3TSqKrmcR/XvVnvzo6p3h5Nc9CdtHdukS25Kp21DUa184LycN5P8YjtAx+WtXkr6AKr4yQHnlQ1HLD2+qlk8OdqU4X9HXYBKYTpplFqR0P65KgJDv5M8h1OlG61AC8wWwYt4jthxcr4S+OV3ww0KSWbJLpEnNArjD9oszSWyVN4ZB3D49eaohmu9ywiQHjAqJUoreb1kd6qFhkmCDeRbZ2aga57X5jjsm5nAO0ejGauGc7QcYBuM2Q4w131etYcdPQP2OZHk8hUJJyPY3nVYrgGXP+KSuVR43RBuJkXAt7XLmC5Be0ceU8cyBb0AxF0WWL8va14W6j65iYeCSeQyAUCUOrTb6N5AivK6HvG5WTFfgsuU4bLFIwGWL9lADy+m6KETqU5bVwmFj0Gdkp5
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

